apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: devops-app
          image: jeff2.jfrog.io/devops-docker/fastapi-app-ls:latest
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: jfrog-pull-secret
---
apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
spec:
  selector:
    app: devops-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort